modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker}"
accessTransformers=[]

[[mods]]
modId="iblis"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[mods]]
modId="iblis_headshots"
version="${mod_version}"
displayName="${headshots_mod_name}"
displayURL="${mod_url}"
authors="${mod_authors}"
description='''
${headshots_mod_description}
'''

[[dependencies.iblis]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.iblis]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.iblis]]
modId="jei"
mandatory=false
versionRange="[15.20,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.iblis_headshots]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.iblis_headshots]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
